// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary1.Models.jobposting
{
    public partial class JobPosting
    {
        public int Id { get; set; }
        public string Descrizione { get; set; }
        public DateTime DataInizio { get; set; }
        public DateTime? DataFine { get; set; }
        public string Riferimento { get; set; }
        public string Annuncio { get; set; }
        public byte[] Pdfannuncio { get; set; }
        public int Idsocieta { get; set; }
        public string Idfunzione { get; set; }
        public bool? RichiediProvincia { get; set; }
        public bool? RichiediTitoloStudio { get; set; }
        public bool? RequisitoLivello { get; set; }
        public bool? RequisitoTipoContratto { get; set; }
        public bool? RichiediComune { get; set; }
        public int? IdtipoProgetto { get; set; }
        public DateTime? DataFineGestori { get; set; }
        public bool? FiltroProvincia { get; set; }
        public bool? RichiediEmail { get; set; }
        public bool? ObbligoInserimentoEmail { get; set; }
        public bool? RichiediTelefono { get; set; }
        public bool? ObbligoInserimentoTel { get; set; }
    }
}