// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary1.Models.jobposting
{
    public partial class JobPostingRequisitiComuni
    {
        public int IdjobPosting { get; set; }
        public string Idcomune { get; set; }
    }
}