// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary1.Models.jobposting
{
    public partial class JobPostingRequisitiLivelli
    {
        public int IdjobPosting { get; set; }
        public int Idcontratto { get; set; }
        public int Idlivello { get; set; }
    }
}