// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary1.Models.jobposting
{
    public partial class JobPostingCandidature
    {
        public int IdjobPosting { get; set; }
        public int Idpersonale { get; set; }
        public DateTime DataCandidatura { get; set; }
        public string Idprovincia { get; set; }
        public string IdtitoloStudio { get; set; }
        public DateTime? DataColloquioRu { get; set; }
        public int? IdesitoColloquio { get; set; }
        public DateTime? DataColloquioTecnico { get; set; }
        public int? IdesitoColloquioTecnico { get; set; }
        public string IdsysUtenteUltimaModifica { get; set; }
        public DateTime? DataUltimaModifica { get; set; }
        public string NoteColloquioRu { get; set; }
        public string NoteColloquioTecnico { get; set; }
        public int? IdesitoSelezione { get; set; }
        public string NoteSelezione { get; set; }
        public int? IdesitoJobPosting { get; set; }
        public bool? RisorsaScelta { get; set; }
        public string Idcomune { get; set; }
        public int Idfabbisogno { get; set; }
        public bool? InteresseLinea { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public DateTime? DataDecorrenzaTrasferimento { get; set; }
        public string EmailRinuncia { get; set; }
        public string NoteCandidaturaAltriProgetti { get; set; }
    }
}