// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary1.Models
{
    public partial class Personale
    {
        public int Id { get; set; }
        public int? Idsocieta { get; set; }
        public string Matricola { get; set; }
        public string CodiceFiscale { get; set; }
        public string Cognome { get; set; }
        public string Nome { get; set; }
        public DateTime? DataNascita { get; set; }
        public string IdcomuneNascita { get; set; }
        public string Idnazione { get; set; }
        public string Sesso { get; set; }
        public byte? IdstatoCivile { get; set; }
        public string IdtitoloStudio { get; set; }
        public byte? IdservizioMilitare { get; set; }
        public string CodiceBadge { get; set; }
        public string AutorizzoPrivacy { get; set; }
        public string AutorizzoDatiSensibili { get; set; }
        public string AutorizzoPromoPi { get; set; }
        public string AutorizzoPromoSocietaConv { get; set; }
        public DateTime? DataAssunzione { get; set; }
        public string IdmotivoAssunzione { get; set; }
        public string IdmodalitaPagamento { get; set; }
        public string IdtipoPosizione { get; set; }
        public string Idprovenienza { get; set; }
        public int? Idcontratto { get; set; }
        public string IdtipoPersonale { get; set; }
        public string IdtipoOrarioLavoro { get; set; }
        public string IdufficioAssegnato { get; set; }
        public DateTime? DataInizioAssegnazione { get; set; }
        public int? IdsocietaApplicato { get; set; }
        public string IdufficioApplicato { get; set; }
        public DateTime? DataInizioApplicazione { get; set; }
        public DateTime? DataFineApplicazione { get; set; }
        public int? IdsocietaAg { get; set; }
        public string IdufficioAg { get; set; }
        public int? Idlivello { get; set; }
        public DateTime? DataLivello { get; set; }
        public int? Idruolo { get; set; }
        public DateTime? DataRuolo { get; set; }
        public int? IdfiguraProfessionale { get; set; }
        public DateTime? DataFiguraProfessionale { get; set; }
        public int? IdfiguraProfessionaleAg { get; set; }
        public int? Idmestiere { get; set; }
        public DateTime? DataMestiere { get; set; }
        public string Idattivita { get; set; }
        public DateTime? DataAttivita { get; set; }
        public DateTime? DataCessazione { get; set; }
        public string IdmotivoCessazione { get; set; }
        public string IdcategoriaProtetta { get; set; }
        public string IdcategoriaEconomica { get; set; }
        public double? PerCentoLavoro { get; set; }
        public DateTime? DataFinePeriodoProva { get; set; }
        public DateTime? DataNominaRuolo { get; set; }
        public DateTime? DataPrimoGiornoLavorato { get; set; }
        public DateTime? DataRiammissione { get; set; }
        public string Stanza { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Ntaccount { get; set; }
        public string Ntdomain { get; set; }
        public string Cellulare { get; set; }
        public string Processo { get; set; }
        public string Attribuzione { get; set; }
        public DateTime? DataUltimaModifica { get; set; }
    }
}