// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ClassLibrary1.Models
{
    public partial class PersonaleContext : DbContext
    {
        public PersonaleContext()
        {
        }

        public PersonaleContext(DbContextOptions<PersonaleContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Personale> Personales { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Personale>(entity =>
            {
                entity.ToTable("Personale");

                entity.HasIndex(e => new { e.DataCessazione, e.DataNominaRuolo }, "IX_ID_DATANASCITA_SESSO");

                entity.HasIndex(e => new { e.Idsocieta, e.Matricola }, "IX_Personale")
                    .IsUnique()
                    .HasFillFactor(90);

                entity.HasIndex(e => e.Matricola, "IX_Personale_Matricola")
                    .HasFillFactor(90);

                entity.HasIndex(e => e.Idsocieta, "Idx_idSocieta")
                    .HasFillFactor(90);

                entity.HasIndex(e => new { e.Idsocieta, e.IdufficioApplicato }, "Idx_idSocieta_idufficioapplicato")
                    .HasFillFactor(90);

                entity.HasIndex(e => e.Ntaccount, "idx_Personale_NTAccount")
                    .HasFillFactor(90);

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Attribuzione)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.AutorizzoDatiSensibili)
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.AutorizzoPrivacy)
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.AutorizzoPromoPi)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("AutorizzoPromoPI");

                entity.Property(e => e.AutorizzoPromoSocietaConv)
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.Cellulare)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CodiceBadge)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.CodiceFiscale)
                    .HasMaxLength(16)
                    .IsUnicode(false);

                entity.Property(e => e.Cognome)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DataAssunzione).HasColumnType("date");

                entity.Property(e => e.DataAttivita).HasColumnType("date");

                entity.Property(e => e.DataCessazione).HasColumnType("date");

                entity.Property(e => e.DataFiguraProfessionale).HasColumnType("date");

                entity.Property(e => e.DataFineApplicazione).HasColumnType("date");

                entity.Property(e => e.DataFinePeriodoProva).HasColumnType("date");

                entity.Property(e => e.DataInizioApplicazione).HasColumnType("date");

                entity.Property(e => e.DataInizioAssegnazione).HasColumnType("date");

                entity.Property(e => e.DataLivello).HasColumnType("date");

                entity.Property(e => e.DataMestiere).HasColumnType("date");

                entity.Property(e => e.DataNascita).HasColumnType("date");

                entity.Property(e => e.DataNominaRuolo).HasColumnType("date");

                entity.Property(e => e.DataPrimoGiornoLavorato).HasColumnType("date");

                entity.Property(e => e.DataRiammissione).HasColumnType("date");

                entity.Property(e => e.DataRuolo).HasColumnType("date");

                entity.Property(e => e.DataUltimaModifica).HasColumnType("smalldatetime");

                entity.Property(e => e.Email)
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.Fax)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Idattivita)
                    .HasMaxLength(12)
                    .IsUnicode(false)
                    .HasColumnName("IDAttivita");

                entity.Property(e => e.IdcategoriaEconomica)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("IDCategoriaEconomica")
                    .IsFixedLength();

                entity.Property(e => e.IdcategoriaProtetta)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .HasColumnName("IDCategoriaProtetta")
                    .IsFixedLength();

                entity.Property(e => e.IdcomuneNascita)
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("IDComuneNascita");

                entity.Property(e => e.Idcontratto).HasColumnName("IDContratto");

                entity.Property(e => e.IdfiguraProfessionale).HasColumnName("IDFiguraProfessionale");

                entity.Property(e => e.IdfiguraProfessionaleAg).HasColumnName("IDFiguraProfessionaleAG");

                entity.Property(e => e.Idlivello).HasColumnName("IDLivello");

                entity.Property(e => e.Idmestiere).HasColumnName("IDMestiere");

                entity.Property(e => e.IdmodalitaPagamento)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .HasColumnName("IDModalitaPagamento");

                entity.Property(e => e.IdmotivoAssunzione)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .HasColumnName("IDMotivoAssunzione");

                entity.Property(e => e.IdmotivoCessazione)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("IDMotivoCessazione");

                entity.Property(e => e.Idnazione)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("IDNazione");

                entity.Property(e => e.Idprovenienza)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .HasColumnName("IDProvenienza");

                entity.Property(e => e.Idruolo).HasColumnName("IDRuolo");

                entity.Property(e => e.IdservizioMilitare).HasColumnName("IDServizioMilitare");

                entity.Property(e => e.Idsocieta).HasColumnName("IDSocieta");

                entity.Property(e => e.IdsocietaAg).HasColumnName("IDSocietaAG");

                entity.Property(e => e.IdsocietaApplicato).HasColumnName("IDSocietaApplicato");

                entity.Property(e => e.IdstatoCivile).HasColumnName("IDStatoCivile");

                entity.Property(e => e.IdtipoOrarioLavoro)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("IDTipoOrarioLavoro")
                    .IsFixedLength();

                entity.Property(e => e.IdtipoPersonale)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("IDTipoPersonale");

                entity.Property(e => e.IdtipoPosizione)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("IDTipoPosizione")
                    .IsFixedLength();

                entity.Property(e => e.IdtitoloStudio)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("IDTitoloStudio");

                entity.Property(e => e.IdufficioAg)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("IDUfficioAG");

                entity.Property(e => e.IdufficioApplicato)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("IDUfficioApplicato");

                entity.Property(e => e.IdufficioAssegnato)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("IDUfficioAssegnato");

                entity.Property(e => e.Matricola)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Nome)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Ntaccount)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("NTAccount");

                entity.Property(e => e.Ntdomain)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("NTDomain");

                entity.Property(e => e.Processo)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Sesso)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Stanza)
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.Telefono)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=;Database=;User Id=;Password=;");
        }
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}